# Generated by Django 4.2.7 on 2023-12-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='default blog description...', max_length=40),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blogpic.jpg', upload_to='blog_thumbnails'),
        ),
    ]
